### ISSUE TITLE
Cast

### ISSUE THREAD

**Issue by CreationStory** [sdfsdfsv/BF1-Cheating-alpha#1]

**Comment by CreationStory** [comment]
I am using custom software and a mousetimer dialogue to make art and then run it through ai upscaling it looks pretty amazing and in using this to access memory using injection(.drawMaxgrange) to take high quality screen shots i am not drawing anything but ur programs hacks. can u tell me where to look for the game recording function or screenshot? i do not play battlefield i just want to use it for art project

**Comment by sdfsdfsv** [comment]
Wow, maybe obs studio or some func like getDC can be used to capture the sreenshot, but the UI would be captured as well. I'm a newbie in hack and willing to see if someone figure out the addresses of UI

**Comment by CreationStory** [comment]
> 

these arent great but look cool check it creationstory.github.io/UnBounds/BFScreenshots
![3](https://user-images.githubusercontent.com/83620116/202970145-cb7e5496-7993-4e65-9fb8-6b8171309e6b.png)
